image:
  repository: "supabase/postgres"
  tag: "17.6.1.005"
# args:
#   - postgres
#   - -c
#   - config_file=/etc/postgresql/postgresql.conf
service:
  port: 5432
persistence:
  enabled: "true"
  size: 5Gi
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
environment:
  - name: POSTGRES_PASSWORD
    type: secret
    secretName: secret-db
    secretKey: password
  - name: POSTGRES_DB
    type: configMap
    configMapName: config-db
    configMapKey: database
