image:
  repository: "supabase/edge-runtime"
  tag: "v1.67.4"
args:
  - start
  - --main-service
  - /home/deno/functions/main
service:
  port: 54321
environment:
  - name: JWT_SECRET
    type: secret
    secretName: secret-jwt
    secretKey: secret
  - name: SUPABASE_URL
    type: svcURL
    component: kong
  - name: SUPABASE_ANON_KEY
    type: secret
    secretName: secret-jwt
    secretKey: anon
  - name: SUPABASE_SERVICE_ROLE_KEY
    type: secret
    secretName: secret-jwt
    secretKey: service
  - name: SUPABASE_DB_URL
    type: DBUri
    user: postgres
  - name: VERIFY_JWT
    type: value
    value: "true"

volumeMounts:
  - name: functions
    mountPath: /home/deno/functions

volumes:
  - name: functions
    persistentVolumeClaim:
      claimName: data-pvc
