apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "supabase.component.fullname" (dict "ctx" . "component" "functions") }}-functions-pvc
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
