#!/bin/bash
set -euo pipefail

# Supabase Values YAML Generator
# Generates values.yaml from template files in values.yaml.d directory

readonly SCRIPT_NAME="$(basename "$0")"
readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly VALUES_DIR="${SCRIPT_DIR}/values.yaml.d"
readonly OUTPUT_FILE="${SCRIPT_DIR}/values.yaml"
readonly BASE_TEMPLATE="_base.tpl"

# Colors for output
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly BLUE='\033[0;34m'
readonly NC='\033[0m' # No Color

# Default options
DRY_RUN=false
VALIDATE_ONLY=false
VERBOSE=false

# Print usage information
usage() {
    cat << EOF
Usage: ${SCRIPT_NAME} [OPTIONS]

Generate values.yaml from template files in values.yaml.d directory

Options:
  -d, --dry-run       Validate configuration without generating output
  -v, --validate      Validate existing values.yaml file
  -V, --verbose       Enable verbose output
  -h, --help          Show this help message

Environment:
  VALUES_DIR          Directory containing template files (default: ${VALUES_DIR})
  OUTPUT_FILE         Output file path (default: ${OUTPUT_FILE})
EOF
}

# Print colored message
log_info() {
    echo -e "${BLUE}[INFO]${NC} $*"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $*" >&2
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $*" >&2
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $*"
}

# Check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Validate yq is installed
validate_dependencies() {
    if ! command_exists yq; then
        log_error "yq is required but not installed. Please install yq:"
        log_error "  brew install yq (macOS)"
        log_error "  snap install yq (Linux)"
        log_error "  or see: https://github.com/mikefarah/yq#install"
        exit 1
    fi
}

# Validate YAML syntax
validate_yaml() {
    local file="$1"
    if ! yq eval '.' "$file" >/dev/null 2>&1; then
        log_error "Invalid YAML syntax in ${file}"
        return 1
    fi
    return 0
}

# Get list of service files excluding special files
get_service_files() {
    find "${VALUES_DIR}" -maxdepth 1 -name "*.yaml" \
        ! -name "header.yaml" \
        ! -name "global.yaml" \
        ! -name "*.tpl" \
        -exec basename {} .yaml \; | sort
}

# Generate values.yaml
generate_values() {
    local temp_file
    temp_file="$(mktemp)"

    log_info "Generating values.yaml..."

    # Add generation info comment at the very beginning
    echo "# !!! AUTO-GENERATED FILE !!!" > "${temp_file}"
    echo "# This file was automatically generated by ${SCRIPT_NAME}" >> "${temp_file}"
    echo "# Generation timestamp: $(date)" >> "${temp_file}"
    echo "# Do not edit this file manually - changes will be overwritten on next generation" >> "${temp_file}"
    echo "" >> "${temp_file}"

    # Add header content
    if [[ -f "${VALUES_DIR}/header.yaml" ]]; then
        cat "${VALUES_DIR}/header.yaml" >> "${temp_file}"
        echo "" >> "${temp_file}"
    else
        log_warn "header.yaml not found"
        echo "# File structure of values.yaml:" >> "${temp_file}"
        echo "# Global configuration" >> "${temp_file}"
        echo "# |-- Service configurations" >> "${temp_file}"
        echo "" >> "${temp_file}"
    fi

    # Add global configuration
    if [[ -f "${VALUES_DIR}/global.yaml" ]]; then
        cat "${VALUES_DIR}/global.yaml" >> "${temp_file}"
        echo "" >> "${temp_file}"
    else
        log_warn "global.yaml not found"
    fi

    # Process each service
    local services=()
    while IFS= read -r service; do
        services+=("$service")
    done < <(get_service_files)

    if [[ ${#services[@]} -eq 0 ]]; then
        log_error "No service files found in ${VALUES_DIR}"
        rm -f "${temp_file}"
        exit 1
    fi

    log_info "Found ${#services[@]} services: ${services[*]}"

    # Generate services section using yq merge
    local yq_script=""
    for service in "${services[@]}"; do
        local service_file="${VALUES_DIR}/${service}.yaml"
        local base_template="${VALUES_DIR}/${BASE_TEMPLATE}"

        if [[ ! -f "${service_file}" ]]; then
            log_warn "Service file ${service}.yaml not found, skipping"
            continue
        fi

        if [[ ! -f "${base_template}" ]]; then
            log_error "Base template ${BASE_TEMPLATE} not found"
            rm -f "${temp_file}"
            exit 1
        fi

        # Validate service file YAML
        if ! validate_yaml "${service_file}"; then
            log_error "Skipping invalid service file: ${service}.yaml"
            continue
        fi

        if [[ -n "${yq_script}" ]]; then
            yq_script+=" * "
        fi

        yq_script+="{\"${service}\": (load(\"${base_template}\") * load(\"${service_file}\"))}"
    done

    if [[ -n "${yq_script}" ]]; then
        if ${VERBOSE}; then
            log_info "Executing yq script: ${yq_script}"
        fi

        yq eval -n "${yq_script}" >> "${temp_file}" 2>/dev/null || {
            log_error "Failed to generate services section"
            rm -f "${temp_file}"
            exit 1
        }
    fi

    # Validate generated output
    if ! validate_yaml "${temp_file}"; then
        log_error "Generated invalid YAML output"
        rm -f "${temp_file}"
        exit 1
    fi

    # Finalize output
    if ${DRY_RUN}; then
        log_success "Dry run completed successfully - output is valid"
        cat "${temp_file}"
        rm -f "${temp_file}"
    else
        mv "${temp_file}" "${OUTPUT_FILE}"
        log_success "Generated ${OUTPUT_FILE} successfully"

        if ${VERBOSE}; then
            log_info "Generated services:"
            for service in "${services[@]}"; do
                echo "  - ${service}"
            done
        fi
    fi
}

# Validate existing values.yaml
validate_existing() {
    if [[ ! -f "${OUTPUT_FILE}" ]]; then
        log_error "File not found: ${OUTPUT_FILE}"
        exit 1
    fi

    if validate_yaml "${OUTPUT_FILE}"; then
        log_success "Existing values.yaml is valid"
    else
        log_error "Existing values.yaml contains errors"
        exit 1
    fi
}

# Parse command line arguments
parse_arguments() {
    while [[ $# -gt 0 ]]; do
        case $1 in
            -d|--dry-run)
                DRY_RUN=true
                shift
                ;;
            -v|--validate)
                VALIDATE_ONLY=true
                shift
                ;;
            -V|--verbose)
                VERBOSE=true
                shift
                ;;
            -h|--help)
                usage
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                usage
                exit 1
                ;;
        esac
    done
}

main() {
    parse_arguments "$@"
    validate_dependencies

    if [[ ! -d "${VALUES_DIR}" ]]; then
        log_error "Values directory not found: ${VALUES_DIR}"
        exit 1
    fi

    if ${VALIDATE_ONLY}; then
        validate_existing
    else
        generate_values
    fi
}

# Run main function
main "$@"
